# Generated by Django 3.0.1 on 2020-02-04 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='date_created',
            new_name='last_created',
        ),
    ]
